#!/bin/sh
#------------------------------------------------------------------------------
# License
#
#     This file is part of the branch "get-em" available here:
#         https://github.com/wyldckat/ThirdParty-2.0.x/commits/get-em
#
#     These modifications have not been endorsed by OpenCFD Ltd nor SGI.
#
#     It's licensed under the same license of the target software, namely GPL
#   v3 or above (see <http://www.gnu.org/licenses/>).
#
#     The target software is OpenFOAM(R) <http://www.openfoam.com>, which is
#   trademarked by and Copyright (C) OpenCFD Ltd.
#
# File
#     etc/tools/get-em/openmpi
#
# Description
#     This script will gather the necessary information about the application.
#     This script expects to be executed in the base folder where the get-em script is.
#
# FIXME
#   * Currently it is hard-coded to use tar.bz2.
#
#------------------------------------------------------------------------------

versionVar="FOAM_MPI"
appName="openmpi"
appDefaultSep="-"
appFileExt="tar.bz2"


#
# Shows the major version based on the whole version.
#
getMajorVersion()
{
  echo $1 | sed -e 's=\(^[0-9]\.[0-9]\).*=\1='
}


#
# Shows the description for this application.
#
GE_showDesc()
{
  echo "openmpi - Retrieve Open MPI source code. Size: 3 to 8MB"
}


#
# Updates the file defined in $versionCacheFile, using the mirror url $1 and
# uses the $testFile as a sandbox.
#
GE_update()
{
  #first check available major versions (>=2.6)
  wget "$1" -O $testFile > /dev/null 2>&1
  LIST_MAJOR_VERSIONS=`grep -e 'v[0-9]\.[0-9]/"' $testFile | \
    sed -e 's=.*ompi/v\(.*\)/".*=\1=' | \
    grep -v -e "^1\.[0-2]" | \
    sort -u`
  [ -r "$versionCacheFile" ] && rm $versionCacheFile

  #now cycle through the major versions and list the available minor versions
  for mjv in $LIST_MAJOR_VERSIONS; do
    wget "$1ompi/v$mjv/" -O $testFile > /dev/null 2>&1
    grep -e "openmpi-[0-9][\.0-9]*\.$appFileExt" $testFile | \
      sed -e 's=.*>\(openmpi-.*\)\.'$appFileExt'<.*=\1=' -e 's_-_=_' | \
      sort -u >> $versionCacheFile
  done

  rm $testFile
}


#
# Receives the mirror url $1, the real version $2 and the variable $appFileExt.
# Shows the full url for the file to be downloaded.
#
GE_geturl()
{
  MAJORVERSION=`getMajorVersion $2`
  echo ${1}ompi/v$MAJORVERSION/downloads/openmpi-$2.$appFileExt
}


#
# Echoes the relative path of the target folder. Receives the real version $1.
#
GE_getfolder()
{
  echo openmpi-$1
}


#
# Echoes the number of folder levels counting from the left that the unpacker
# should drop. This is (or at least it should be) a prevention mechanism for
# tar/zipbombs.
#
GE_levels()
{
  echo 1
}


# Finally source the master script
. etc/tools/get-emScriptFunctions
