#!/bin/sh
#------------------------------------------------------------------------------
# License
#
#     This file is part of the branch "get-em" available here:
#         https://github.com/wyldckat/ThirdParty-2.0.x/commits/get-em
#
#     These modifications have not been endorsed by OpenCFD Ltd, SGI corp nor
#   the OpenFOAM Foundation.
#
#     It's licensed under the same license of the target software, namely GPL
#   v3 or above (see <http://www.gnu.org/licenses/>).
#
#     The target software is OpenFOAM(R) <http://www.openfoam.com>, which is
#   trademarked by and Copyright (C) OpenFOAM Foundation.
#
# File
#     etc/tools/get-em/paraview
#
# Description
#     This script will gather the necessary information about the application.
#     This script expects to be executed in the base folder where the get-em script is.
#
# FIXME
#   * Currently it is hard-coded to use tar.gz.
#
#------------------------------------------------------------------------------

versionVar="ParaView_VERSION"
appName="ParaView"
appDefaultSep="" #none needed
appFileExt="tar.gz"


#
# Shows the major version based on the whole version.
#
getMajorVersion()
{
  echo $1 | sed -e 's=\(^[0-9]\.[0-9]*\).*=\1='
}


#
# Shows the description for this application.
#
GE_showDesc()
{
  echo "paraview - Retrieve ParaView source code. Size: 25 to 40MB"
}


#
# Updates the file defined in $versionCacheFile, using the mirror url $1 and
# uses the $testFile as a sandbox.
#
GE_update()
{
  #first check available major versions (>=2.6)
  wget "$1" -O $testFile > /dev/null 2>&1
  LIST_MAJOR_VERSIONS=`grep -e "v[3-9]\.[0-9]*/" $testFile | \
    sed -e 's=.*>\(v.*/\)</a.*=\1=' -e 's=/==' -e 's=v==' | \
    grep -v -e "^3\.[0-6]$" | \
    sort -u`
  [ -r "$versionCacheFile" ] && rm $versionCacheFile

  #now cycle through the major versions and list the available minor versions
  for mjv in $LIST_MAJOR_VERSIONS; do
    wget "$1/v$mjv/" -O $testFile > /dev/null 2>&1
    grep -e "ParaView-[0-9]\.[0-9]*\.[0-9]*\.$appFileExt" $testFile | \
      sed -e 's=.*>\(ParaView-.*\)\.'$appFileExt'<.*=\1=' -e 's_-_=_' | \
      sort -uV >> $versionCacheFile
  done

  sort -V $versionCacheFile > $testFile
  cat $testFile > $versionCacheFile
  rm $testFile
}


#
# Receives the mirror url $1, the real version $2 and the variable $appFileExt.
# Shows the full url for the file to be downloaded.
#
GE_geturl()
{
  MAJORVERSION=`getMajorVersion $2`
  echo ${1}v$MAJORVERSION/ParaView-$2.$appFileExt
}


#
# Echoes the relative path of the target folder. Receives the real version $1.
#
GE_getfolder()
{
  echo ParaView-$1
}


#
# Echoes the number of folder levels counting from the left that the unpacker
# should drop. This is (or at least it should be) a prevention mechanism for
# tar/zipbombs.
#
GE_levels()
{
  echo 1
}


# Finally source the master script
. etc/tools/get-emScriptFunctions
