#!/bin/sh
#------------------------------------------------------------------------------
# License
#
#     This file is part of the branch "get-em" available here:
#         https://github.com/wyldckat/ThirdParty-2.0.x/commits/get-em
#
#     These modifications have not been endorsed by OpenCFD Ltd nor SGI.
#
#     It's licensed under the same license of the target software, namely GPL
#   v3 or above (see <http://www.gnu.org/licenses/>).
#
#     The target software is OpenFOAM(R) <http://www.openfoam.com>, which is
#   trademarked by and Copyright (C) OpenCFD Ltd.
#
# File
#     etc/tools/get-em/tecio
#
# Description
#     This script will gather the necessary information about the application.
#     This script expects to be executed in the base folder where the get-em script is.
#
# FIXME
#   * Currently it is hard-coded to use zip.
#
#------------------------------------------------------------------------------

versionVar="tecio_version"
appName="tecio"
appDefaultSep="" #none needed
appFileExt="zip"


#
# Shows the description for this application.
#
GE_showDesc()
{
  echo "tecio - Retrieve Tecplot's <tecplot.com> TecIO source code. Size: 200 to 300kB"
}


#
# Updates the file defined in $versionCacheFile, using the mirror url $1 and
# uses the $testFile as a sandbox.
#
GE_update()
{
  #first check available major versions (>=2.6)
  wget "$1" -O $testFile > /dev/null 2>&1
  LIST_MAJOR_VERSIONS=`grep -e "/tecio/[0-9]*/" $testFile | \
    sed -e 's=.*/tecio/\([0-9]*\).*=\1=' | \
    grep -v -e "^3[0-9]*" | \
    grep -v -e "^200[0-8]" | \
    sort -u`
  [ -r "$versionCacheFile" ] && rm $versionCacheFile

  #now cycle through the major versions and list the available minor versions
  for mjv in $LIST_MAJOR_VERSIONS; do
    wget "$1/$mjv/" -O $testFile > /dev/null 2>&1
    grep -e "tecio[0-9]*\.$appFileExt" $testFile | \
      sed -e 's=.*>\(tecio.*\)\.'$appFileExt'<.*=\1=' -e 's_tecio_tecio=_' | \
      sort -u >> $versionCacheFile
  done

  rm $testFile
}


#
# Receives the mirror url $1, the real version $2 and the variable $appFileExt.
# Shows the full url for the file to be downloaded.
#
GE_geturl()
{
  echo ${1}$2/tecio$2.$appFileExt
}


#
# Echoes the relative path of the target folder. Receives the real version $1.
#
GE_getfolder()
{
  echo tecsrc
}


#
# Echoes the number of folder levels counting from the left that the unpacker
# should drop. This is (or at least it should be) a prevention mechanism for
# tar/zipbombs.
#
GE_levels()
{
  echo 1
}


# Finally source the master script
. etc/tools/get-emScriptFunctions
